twisted/txmongo

tests/mongod.py, tests/test_auth.py, txmongo/collection.py, txmongo/connection.py, txmongo/database.py, txmongo/protocol.py
Hi!
The current implementation of authentication is broken in several use cases:
* It is not reenterant and this leads to bugs with ConnectionPool when pool_size > 1. In such case ConnectionPool.authenticate_with_nonce() might be called multiple times simultaneously and race-condition occurs because 'getnonce' and 'authenticate' MongoDB commands cannot be mixed up.
* It makes assumption that authentication on some DB is only required when accessing this DB. But MongoDB allows user from DB1 to have permissions on DB2.
I've reworked all auth-related stuff and added some unit tests, some of them are failing on master branch.
*Please note that unit tests in test_auth.py require your local MongoDB to have auth=true, no configured users and localhost exception enabled.*
=> Authentication reimplemented to work well with ConnectionPool and with multiple DBs

tests/test_auth.py, txmongo/connection.py
Recent authentication-related changes broke compatibility with Twisted ≤ 13.1.0 because DeferredList doesn't support generators.
Issue reported as #75
=> Fixed regression on Twisted<=13.1.0

tests/test_queries.py, txmongo/collection.py
I have fixed same problems with `limit=` in `find_with_cursor()` as 477f34a1190b272265f1702e3e11875a58457125 fixed for `find()`
After that I noticed that `find()` and `find_with_cursor()` are almost identical while `find_with_cursor()` is the superset of `find()`. So, 539ca559b9be06715f9094c61da45cb068601538 replaces `find()` implementation with simple code that unwinds result of `find_with_cursor()`.
I don't see any way compatibility or something might be broken because they do literally the same, including error-handling (i.e. absense of it :) ).
=> find() as wrapper around fixed find_with_cursor()

txmongo/connection.py, txmongo/protocol.py
Support for SCRAM-SHA-1 authentication protocol. It was introduced in MongoDB 2.8 and became default in 3.0+.
`ConnectionPool.authenticate()` now accepts `mechanism` optional argument that might be used to force MONGODB-CR auth protocol with MongoDB 3.0+. Default is to autodetect protocol from server wire protocol version.
=> SCRAM-SHA-1 authentication

tests/test_queries.py, txmongo/collection.py
PyMongo 3.0 removed `as_class` argument from BSON.decode as stated in #80
This fix adapts txmongo to this change by using new `CodecOptions` class from PyMongo 3.0 while falling back to `as_class` on 2.x.
Also testcase added for checking `as_class` behavior.
=> Fixed 'as_class' argument of find() and find_one() with pymongo 3.0

tests/test_queries.py
test_queries.py was using new-style dict comprehension syntax that was introduced in Python 2.7.
=> New-style dict literal replaced with dict(...) for the sake of python2.6

tests/test_aggregate.py, tests/test_collection.py, tests/test_queries.py
Python 2.6 doesn't have OrderedDict, so I replaced it with custom one-line `dict` subclass for testing `as_class` parameter of `find()`
=> OrderedDict replaced by custom dict subclass for the sake of py26

txmongo/protocol.py
Somewhy I was using subscription syntax for __builtins__ module instead of dot syntax (don't know why :)). This is not supported by PyPy.
=> __builtins__["len"] -> __builtins__.len for PyPy

tests/test_protocol.py
A bunch of tests that encode protocol messages into bytes and then decode them using `txmongo.protocol.MongoDecoder` and compare decoded object with original request object.
This might be considered as additional check for encoding code. Also this will add test coverage for `MongoDecoder` class.
=> Tests that encode and decode protocol messages and compare results

tests/test_aggregate.py, tests/test_connection.py, tests/test_objects.py, tests/test_queries.py
I've looked into sporadically failed tests and found that this happens for tests that create MongoConnection and immediately call its disconnect() without issuing any queries. MongoConnection() constructor starts connecting in background. Connection process in turn starts name resolution of "localhost" into ip-address. If name resolution doesn't finish until disconnect() returns (it takes exactly 1 main loop round-trip), trial fails with "reactor unclean". (Name resolution is deferred to separate thread, so there is race condition which fails more often on slow machines).
Unfortunately, I didn't found any good way to wait until name resolution is done :(
The simpliest way to solve this is to change "localhost" to "127.0.0.1" in test_queries.py, test_aggregate.py and test_connection.py. Or …
=> Trying to fix "reactor unclean" test fails

tests/mongod.py, tests/test_auth.py, tests/test_replicaset.py, txmongo/connection.py, txmongo/protocol.py
I've noticed that txmongo doesn't work with failover of replicaset as expected. It should raise AutoReconnect and client code should be able to re-issue query immediately.
Instead, txmongo raises ConnectionDone and immediate retry raises may fail with same exception.
Also, txmongo duplicated records in hosts list if same hosts were specified in connection URI and auto-discovered from replicaset config.
This PR fixes this and also introduces some testcases for replicaset.
The downside is that tests from `test_replicaset.py` are extremely slow. They are taking around 1 minute on my machine (combined) while all other tests take 3 seconds. That's because they need to deploy 3 mongod processes, configure replicaset, wait until it synced, and the slowest: wait until mongods will elect new …
=> Failover fixed and covered with unittests

tests/test_collection.py, txmongo/database.py
I've added tests for `coll.rename()` and `coll.options()`
While testing `Collection.rename()` I've also noticed a typo in `Database.__call__()` that made `Collection.rename()` completely non-working :)
=> coll.rename() fix and additional tests

tests/test_auth.py, tests/test_collection.py, tests/test_filters.py, tests/test_queries.py, tests/test_replicaset.py, txmongo/collection.py, txmongo/database.py
Signature and behavior are same as in PyMongo
Almost all occurences of `db["$cmd"].find_one()` replaced with this new method.
Since `db.command()` has integrated simple error-checking, redundant checks were removed in some methods that are using this new method.
=> db.command() method

tests/test_collection.py, txmongo/database.py
If `create_collection` is failing, it doesn't calls errback on deferred it returns, so calling code will hang forever
=> Proper failure of create_collection instead of hang in case of error

tests/test_collection.py, tests/test_find_and_modify.py, tests/test_queries.py, txmongo/collection.py
Before refactoring some methods of `collection.py` to use `inlineCallbacks`, i'd like to have each code path covered by tests.
Now `collection.py` is 100%-covered except for lines that should never  be reached or should not be reached with library versions we use in testing environment (pymongo==3.0).
While doing tests for `map_reduce()` I've found typo that made it useless without `full_response=True` :)
=> Additional tests for collection.py and small fix for map_reduce()

tests/test_collection.py, tests/test_find_and_modify.py, txmongo/collection.py, txmongo/connection.py, txmongo/database.py
I've refactored a bunch of methods to use inlineCallbacks-style where it is applicable.
Main exception is the `find_with_cursor()` which has unusual recurring deferreds semantics.
As a consequence, a couple of tests were altered to use `assertFailure` instead of `assertRaises` since `@inlineCallbacks` returns failed deferred in case of errros instead of direct raising exceptions.
=> inlineCallbacks everywhere

tests/test_objects.py, txmongo/_gridfs/__init__.py, txmongo/_gridfs/grid_file.py, txmongo/gridfs.py
fix missing os.SEEK_END, use undocumented version since with tests only work with twisted >= 15
removed unsupported APIs, as they are from the 1.5 time. no need to carry them forward
adding GridFS .put .get coverage
=> dropping support python <= 2.5, small tidy-ups, expanding test coverage

docs/source/NEWS.rst, tests/test_queries.py, txmongo/collection.py
This change relates only to `find_one`, `find` still returns empty list when nothing was found
=> find_one() modified to return None instead of {} when nothing found

txmongo/connection.py, txmongo/database.py
A couple of new features appear to be broken on PyMongo 2.8. This patch fixes compatibility.
=> Recently added features fixed to be compatible with PyMongo 2.8

txmongo/protocol.py
This flag is missing in `txmongo.protocol`, so there is no way to make unordered bulk insert
=> INSERT_CONTINUE_ON_ERROR flag for insert()

requirements-dev.txt, tests/test_write_concern.py, tox.ini, txmongo/collection.py, txmongo/connection.py, txmongo/database.py, txmongo/protocol.py, txmongo/write_concern.py
API closely resembles PyMongo
* `MongoConnection` and `ConnectionPool` now takes write-concern options as named args and as URI options (named args take precedence)
* You can set override write-concern for `Database` and `Collection` when creating them using constructors (`db = Database(conn, "dbname", write_concern=WriteConcern(...)`). In this case write concern is specified using instance of special `WriteConcern` class. It is copied to txmongo source tree from PyMongo 3.0 because it doesn't exist in 2.8.
* `insert`, `update`, `save` and `remove` now takes both `safe` argument and write-concern named arguments. Semantics is the same as in PyMongo 2.x:
* named args (`w`, `wtimeout`, `j`, `fsync`) take precedence over `safe`
* `safe=False` forces query to be unacknowledged
* `safe=True` …
=> Write concern

tests/test_objects.py, tests/test_replicaset.py, txmongo/_gridfs/__init__.py
=> use inlinecallbacks, added tests

tests/test_queries.py, txmongo/collection.py
Implementation of new-style query methods of PyMongo 3.0:
- `insert_one`, `insert_many`
- `update_one`, `update_many`
- `replace_one`, `replace_many`
- `delete_one`, `delete_many`
- `find_one_and_delete`, `find_one_and_update`, `find_one_and_replace`
All new methods (except `find_one_and_***` ones) return `pymongo.results.***Result` instances just like PyMongo's counterparts.
**WARNING: This code breaks compatibility with PyMongo 2.x** by using classes which are only available in PyMongo 3.0
List of what we use from PyMongo 3.0:
- `pymongo.results.***Result`
- `pymongo.common.validate_ok_for_update`, `pymongo.common.validate_ok_for_replace`
- `pymongo.collection.ReturnDocument`
All these are just simple helper classes and functions. So we have two options:
1. Drop support with PyMongo …
=> New query methods

.travis.yml, tests/mongod.py, tests/test_auth.py, tests/test_collection.py, txmongo/connection.py, txmongo/database.py
`test_auth.py` expoits a hack to force MongoDB to use obsolete MONGODB-CR auth mechanism in order to get coverage of both SCRAM-SHA-1 and MONGODB-CR auth methods.
Travis environment changed to use MongoDB 3.0
=> Testing MONGODB-CR auth method

docs/source/NEWS.rst, requirements-dev.txt, tests/test_auth.py, tox.ini, txmongo/connection.py
I didn't cherry-picking because original tests for auth mechanisms in 15.1.0 require `db.command` which depend on PyMongo 3.0. So I added another testing code.
Is it ok that I inserted 15.0.1 in NEWS.rst?
=> ?authMechanism URI option support backported from 15.1.0 to 15.0.0

tests/test_queries.py
=> Fixed unacknowledged insert_many tests on MongoDB 3.2

docs/source/NEWS.rst, tests/test_queries.py, txmongo/collection.py, txmongo/connection.py
`insert_many` reimplemented to make it able to insert more than 1000 documents or more than 16Mb of documents at once. It now automatically splits documents into batches when reaching MongoDB limits (1000pcs or 16Mb).
Fixes #149
=> Insert more than 1000 documents with insert_many

docs/source/NEWS.rst, txmongo/_gridfs/grid_file.py
I've also changed `kb` into `KB` (assuming it was a typo)
=> Change GridFS's default chunkSize to 255kB

tests/test_objects.py, txmongo/_gridfs/__init__.py
As talked in #160 
I've also corrected missing `yield` in `db.fs.files.remove({})` which lead to concurrency errors
=> GridFS.get raises NoFile if file is not found

docs/source/NEWS.rst, tests/test_queries.py, txmongo/collection.py
`fields` projection parameter seems to be completely pointless for `count()`
I don't think removing it could break any existing code.
Also added distinct test case for `count()`
=> fields parameter removed for count()

txmongo/_gridfs/__init__.py
Missing `yield` makes `GridFS.put` returns before the file is actually written in GridFS
=> Fix GridFS.put yield on close

txmongo/collection.py
I've initially planned to make a PR when I finish writing docs for all `Collection` and `Database` methods. But all these docstrings need proof-reading and fact-checking. And writing and proof-reading can be done in parallel if I release early.
Texts are partly stolen from PyMongo, partly written from scratch. Please excuse and fix my poor English.
=> Better docs

docs/source/NEWS.rst, tests/test_objects.py, txmongo/_gridfs/__init__.py
Correction for #164
This PR is based on PR #163 (needed to make the unit tests work), only commit 059355c1a8cb0438c4e46121820fc21895e6fc2c should be considered
=> GridFS ensure indexes is done without yielding

tests/mongod.py, tests/test_replicaset.py, txmongo/connection.py
TxMongo was unable to detect hanging connection to MongoDB.
This patch adds deadline to `ismaster` query that txmongo sends every 300s to handle this case.
Issues:
- Currently `ismaster` is sent every 300s. This seems too rare for production environment, imho. We need to make it configurable or choose some Value That Fits Them All™ (if it even exists).
=> Handling stale connection

docs/source/NEWS.rst, tests/test_bulk.py, tests/test_queries.py, tests/utils.py, txmongo/collection.py
Implementation of PyMongo's `Collection.bulk_write()` method.
Some internals of PyMongo used to avoid copy-pasting.
=> Collection.bulk_write()

txmongo/collection.py
`bulk_write()` was not propagating exceptions (`AutoReconnect`, for example) when used with `ordered=False`
=> Fixed handling of connection errors in bulk_write

tox.ini
Twisted team changed something in either Trial or `twisted.python.reflect` and now our `trial tests` says `can't find module "tests"`. I'm not sure if it is a bug in Twisted and whether it will be fixed, but lets fix this on our side for now.
=> fixing tests against twisted-trunk

docs/source/NEWS.rst, tests/test_codec_options.py, txmongo/collection.py, txmongo/connection.py, txmongo/database.py
We have used `pymongo.bulk._Bulk` internal class to implement bulk ops. But since PyMongo 3.3.0 that was released a week ago, this class assumes that `Collection` has proper support of codec options.
This patch adds `codec_options` to `ConnectionPool`, `Database` and `Collection` classes and `codec_options` kwarg to `Collection.with_options()`. This fixes our test suite that is failing since PyMongo 3.3 release.
I've also added notice in NEWS.rst that `Collection.with_options` should be preferred now instead of `as_class` kwags to `find`. PyMongo had dropped `as_class` kwags in 3.0.
=> support for codec_options

tests/test_replicaset.py, txmongo/connection.py
It turns out that low default values prevents us from issuing long-running queries
=> default watchdog timeouts increased

tests/test_collection.py, txmongo/collection.py
`Collection.index_information` and `Collection.options` are depending on `db.system.indexes` and `db.system.namespaces` which are not exist when running on WiredTiger.
This patch fixes `index_information()` and `options()` by using new-in-3.0 `listIndexes` and `listCollection` commands.
Both new commands return results in the new-style cursor specification document which we are not able to properly unwind (yet). So, `assert`-ing that all results are coming in one batch. I think this is ok because it is hard to imagine the amount of indexes or collection whose info wouldn't fit in 16Mb.
=> Tests fixed when running with WiredTiger

docs/source/NEWS.rst, txmongo/collection.py
TxMongo has the serious bug: if sorting specification or hint contains several fields, it gets transformed to a `dict` before issuing the query, so the real fields order in BSON is undefined and so ordering is undefined too.
This patch fixes it by using `SON` instead of `dict`. Unfortunately, I can't imagine how to make an unintrusive test case for this except making `Collection.__apply_find_filter` non-private and test by calling it.
=> Multi-key sort specs and hints fixed

.travis.yml, tests/mongod.py, tests/test_auth.py, tests/test_filters.py, tox.ini, txmongo/collection.py
Small tests improvements:
• `test_replicaset.py` was using 3 GB of temporary disk space (1GB oplog per 3 `mongod` instances)
• `test_auth.py` might leak directories in `/tmp` when ran against MongoDB v3
• Not testing with py26
• Test all supported configurations: py27 + Twisted ≥14, py3x + Twisted ≥16, pypy + Twisted ≥14
But the number of test configurations doubled, which will make Travis tests to run longer
=> Various tests fixes

tests/test_objects.py
Twisted team changed `twisted._version.version` to `twisted._version.__version__` in https://github.com/twisted/twisted/commit/5c1777777f85aaf799c2269f9f5dddcf0d59803e
=> New way of getting Twisted version in trunk version

docs/source/NEWS.rst, tests/test_objects.py, txmongo/_gridfs/__init__.py, txmongo/collection.py, txmongo/database.py
It is funny and sad at the same time, but GridFS were creating index with a typo in field name and nobody noticed that :)
Also, `ensure_index` removed from `get_last_version` because ASC+ASC index, created in `__init__` is sufficient.
For the means of testing indexes creation, I've added `codec_options` argument to `Database.command()`. It can be used to make `command()` to return response as `SON` instead of plain `dict`.
=> GridFS index fixed. codec_options argument for Database.command.

docs/source/NEWS.rst, tests/test_connection.py, txmongo/connection.py
API is following PyMongo's `MongoClient.drop_database()`
=> ConnectionPool.drop_database

docs/source/NEWS.rst, tests/test_cancel.py, tests/test_replicaset.py, txmongo/connection.py
*This PR is not for merging now, but mostly for discussion of the issue and the ways of solution*
Checking regularly that server nodes that we are connected to are alive and dropping connections if they are not.
This is one of possible approaches to solve the issue: if the network link is disappears between us and MongoDB server, how can we deal with it?
Currently TxMongo regularly sends `ismaster` command to all connections in the pool and drops connection if no answer received within a timeout. But this has a downside: if connection is waiting for a very long-running query, it won't receive `ismaster` response and will be dropped by this watchdog procedure.
What do you think about suggested technique? Does it cover all the scenarios? Can the code be simplified?
=> Pinging server(s) and drop connections if server is gone

docs/source/NEWS.rst, tests/test_collection.py, tests/test_queries.py, txmongo/collection.py
Continuing #55
I suggest to change signature of `find()`, `find_with_cursor()` and `find_one()` to more closely match PyMongo's counterparts.
Now it is `(spec=None, skip=0, limit=0, fields=None, filter=None, cursor=False, **kwargs)`
I'm proposing to change it to `(spec=None, projection=None, skip=0, limit=0, filter=None, **kwargs)`
It can be breaking if done immediately, but we can do it with deprecation interval. This PR makes `find*()` to accept both old and new signatures with issuing DeprecationWarning for the old one.
* Short form `find({'x': 1}, {'_id': 0})` becames compatible with PyMongo
* Keyworded form `find({'x': 1}, projection={'_id': 0})` too
* I suggest to deprecate `cursor` argument to `find()` in favor of `find_with_cursor()`. `cursor=True` changes behavior and semantics …
=> New signature for find() method and compatibility with old one

docs/source/NEWS.rst, txmongo/collection.py
When implementing `bulk_write` I did the same mistake that was once fixed in #140 for `find_with_cursor`. 
In CPython, inner function referencing itself creates circular reference between function object and its closure. Quick proof:
```python
def f():
def g():
g()
print(gc.get_count()[0])
for _ in range(100000): f()
print(gc.get_count()[0])
```
It outputs something like `428` and `300395`, which means that each call to `f()` leaves 3 non-collected objects for GC. Note that `g()` is not even called.
This patch removes such circular-references in `Collection._execute_bulk` and `Collection._execute_batch_command` in a ugly but working way: by passing function references as arguments into the functions themselves.
```python
before = gc.get_count()[0]
for i in range(10000): …
```
=> gc optimization in Collection.bulk_write

docs/source/NEWS.rst, tests/test_auth.py, txmongo/connection.py
Use 'authsource' as auth database, if specify in uri, and orig database if not.
https://docs.mongodb.com/manual/reference/connection-string/#urioption.authSource
=> Auth using authsource db

tests/test_queries.py, txmongo/collection.py
I've noticed that several tests were failing against modern MongoDB 3.4
1. https://github.com/twisted/txmongo/compare/master...IlyaSkriblovsky:mongodb-3.4-tests-fixed?expand=1#diff-cecc483f704c4be15eaed66c3bb3678bL302
MongoDB 3.4 [changed behavior of the first batch of `find()` command](https://docs.mongodb.com/v3.4/tutorial/iterate-a-cursor/#cursor-batches). Before it was returning maximum of 1mb in the first batch, now this restriction is loosened, so this test fails. Actually I think this test is redundant, it was checking that negative limit forces only the single batch in result. It is not our concern anyways.
2. https://github.com/twisted/txmongo/compare/master...IlyaSkriblovsky:mongodb-3.4-tests-fixed?expand=1#diff-cecc483f704c4be15eaed66c3bb3678bL384
MongoDB 3.4 changed error …
=> Tests fixed for MongoDB 3.4

.travis.yml, docs/source/NEWS.rst, tox.ini, txmongo/collection.py
I tried to fix Travis CI issue noticed in #219, but went a bit too far :)
(this PR includes changes from #219 in order to pass tests with PyMongo 3.6)
Seems like updated Travis' `trusty` environment doesn't starts newly-installed mongodb-org-server anymore. So I've added manual `mongod` run in `before_install`.
Then build started to fail with tox wasn't able to find Python 3.3... I have no idea of what have changed on the Travis' side, but anyways our previous Travis config seems a bit strange because it ran all py2.7–3.5 tests with `python: 2.7` in .travis.yml... So I decided to make it a bit more clear.
• Manually starting mongod since updated Travis' `trusty` image doesn't starts it after installation anymore
• More clean testing matrix configuration
• Removed testing on Python 3.3 …
=> Fixing and cleaning Travis CI configuration

docs/source/NEWS.rst, txmongo/collection.py
PyMongo 3.6 changed behavior of private `pymongo.helpers._check_write_command_response()` function. I've copied it into `txmongo.collection` to avoid future compatibility issues.
See #218
=> Fixing compatibility with pymongo 3.6

docs/source/NEWS.rst, tests/test_aggregate.py, txmongo/collection.py
Mongo 3.6 requires either an `explain` or a `cursor` option with the `aggregate` command. This update adds a `cursor` option with a default initial batch size of `0` (which allows the cursor to quickly return without doing work in case of an error -- see [Mongo docs](https://docs.mongodb.com/manual/reference/method/db.collection.aggregate/#example-aggregate-method-initial-batch-size)
Without this, any `aggregate` query will fail in Mongo 3.6+
This patch gets it back running again, but does not expose the `cursor` option to the calling command. Should it provide a default and also allow that option to be set? The cursor option is a dictionary, but looking at the docs, it _appears_ that it only has one key -- `batchSize`, so I would think we could just expose `initial_batch_size` as a …
=> Fix aggregate with Mongo 3.6

docs/source/NEWS.rst, tests/test_protocol.py, tests/test_queries.py, txmongo/collection.py, txmongo/protocol.py
Added optional batchsize parameter in find_with_cursor (collection.py)
Related: cursors may time out (cursorTimeout ...) Added handling for CursorNotFound in handle_REPLY (protocol.py) 
Added test for batchsize: 
test_FindWithCursorBatchsize (tests.test_queries.TestMongoQueries)
test_FindWithCursorBatchsize ... ok
The proposed changed builds on the default behavior of Collection.find_with_cursor. 
When issuing the initial request 101 documents are returned, the remainder of the documents are returned upon the next iteration (yielding on the deferred returned in the initial request)
This change allows one to configure the number of documents to be returned per iteration.
It helps heavily loaded clients to control their resources, when working with large collections.
An alternative approach …
=> Added support for batchsize parameter in collection.py/

docs/source/NEWS.rst
Changelog entry for #226 seems to be mistakenly added to already released 18.0.0 instead of pending 18.1.0 release.
See https://github.com/twisted/txmongo/pull/226#issuecomment-373710445
=> Changelog entry for PR #226 moved to 18.1.0 UNRELEASED

docs/source/NEWS.rst, txmongo/protocol.py
`MongoProtocol.connectionLost` uses single shared `AutoReconnect` instance to fail many different Deferreds. It took me a day of debugging and not a single gray hair to figure out that logged stack traces of unhandled failures may be very weird in this case.
Proof:
```python
import sys
from twisted.internet.defer import Deferred, inlineCallbacks
from twisted.python import log
log.startLogging(sys.stdout)
@inlineCallbacks
def task1(d):
try:
yield d
except ZeroDivisionError as e:
print('task cought')
@inlineCallbacks
def task2(d):
yield d
d1 = Deferred()
d2 = Deferred()
task1(d1)
task2(d2)
error = ZeroDivisionError('boom')
d1.errback(error)
d2.errback(error)
```
This prints:
```
2018-03-16 16:20:28+0300 [-] Log opened.
2018-03-16 16:20:28+0300 [-] task cought
2018-03-16 16:20:28+0300 [-] …
```
=> Do not reuse exception instances

docs/source/NEWS.rst, tests/test_bulk.py, txmongo/collection.py
If Bulk operation is interrupted (by failover, by network failure, ...) current version of txmongo with combination of PyMongo 3.6.0 raises KeyError from `coll.bulk_write`. This is because we are calling `pymongo.bulk._merge_command` without checking it for being proper bulk response.
=> Fixing KeyError when bulk operation is interrupted (for example by failover)

docs/source/NEWS.rst, tests/test_bulk.py, txmongo/collection.py, txmongo/protocol.py
Fixing #232 
Copy-pasted some internal pymongo utility methods into txmongo so future pymongo updates won't break txmongo.
=> Compatibility with PyMongo 3.7

docs/source/NEWS.rst, tests/mongod.py, tests/test_bulk.py, tests/test_filters.py, tests/test_queries.py, txmongo/collection.py, txmongo/protocol.py
Fixing some test failures when running against MongoDB 3.6. TxMongo works fine with 3.6, this issue only affects testing code that hardcodes some error message texts and other internal MongoDB stuff from 3.4. No user-visible changes here.
This PR is based on #233 and includes its commits, so it should be merged only after that.
=> Tests fixed with MongoDB 3.6

docs/source/NEWS.rst, tests/test_collection.py, txmongo/database.py
This is in line with the pymongo [behavior][0], and will make it easier to migrate code from pymongo to txmongo.
[0]: https://github.com/mongodb/mongo-python-driver/blob/3.7.2/pymongo/database.py#L304
=> Allow collection options to be passed only via kwargs

setup.py, txmongo/connection.py
As reported in #247 we didn't support monogdb+srv:// although PyMongo supports it since 3.6.
This PR adds mongodb+srv scheme with "extra" `[srv]` dependency because corresponding feature in PyMongo requires same extra dependency too.
So to have mongodb+srv working txmongo should be installed like this: `pip install txmongo[srv]`.
=> support for mongodb+srv:// uri scheme

docs/source/NEWS.rst, docs/source/conf.py, python-txmongo.spec, setup.py
I think we need to release because currently `pip install txmongo` results in broken installation due to #252
=> 19.2.0 release

txmongo/connection.py
This could raise AssertionError if connection stopped within 10 seconds
Fixes #259
=> checking if LoopingCall is running before stopping it

.travis.yml
Current versions of Twisted dropped support for 2.7.
Actually, we need to update Twisted versions list in .travis-ci.yml, leaving it to the next PR.
=> Don't test against latest Twisted with Python 2.7

txmongo/collection.py, txmongo/database.py, txmongo/pymongo_internals.py
`_check_command_response` vendored from PyMongo 3.10.
Fixes #266
=> Compatibility with PyMongo 3.11

txmongo/connection.py, txmongo/protocol.py, txmongo/utils/__init__.py
Hi.
As is reported in #236, error messages in exceptions raised by txmongo are sometimes ambiguous.
The reason is that txmongo only picks the field `err`, which is not present all the time even if there are actual errors. I cannot find a detailed and exhaustive documentation for all possible fields (there are some related documentations, but for example, none of them formally documents the existence of the field `codeName`). But at least, there are `codeName`, and `errmsg` in recent MongoDB versions.
This PR is going to fix the problem by fall backing to `codeName` and `errmsg` when `err` is not present. It picks any of the three fields whichever is present. 
It should partially fix #236, giving a detailed error message:
`TxMongo: AtlasError: no SNI name sent, make sure using a MongoDB …
=> Fix retrieving error messages

docs/source/status.rst, examples/deferreds/insert.py, txmongo/_gridfs/__init__.py, txmongo/_gridfs/grid_file.py
There are small typos in:
- docs/source/status.rst
- examples/deferreds/insert.py
- txmongo/_gridfs/__init__.py
- txmongo/_gridfs/grid_file.py
Fixes:
- Should read `propagate` rather than `propogate`.
- Should read `underlying` rather than `underlaying`.
- Should read `success` rather than `succes`.
- Should read `maintenance` rather than `maintance`.
Closes #275
=> docs: fix a few simple typos

.github/workflows/txmongo.yml, requirements-dev.txt, tests/test_auth.py, tests/test_count.py, tests/test_get_version.py, tests/test_replicaset.py, tox.ini
Added support via https://github.com/supercharge/mongodb-github-action which supports replicasets and authentication... so we'll need to figure how best to support that feature set with how we test things.
I like that we dockerize mongodb... but means we need to figure out how to run our tests better.
=> initial github actions support

docs/source/NEWS.rst, requirements.txt, setup.py, tests/basic/test_bulk.py, tests/basic/test_collection.py, tests/basic/test_write_concern.py, txmongo/collection.py, txmongo/connection.py, txmongo/database.py, txmongo/protocol.py, txmongo/pymongo_internals.py
PyMongo 4 has a couple of incompatibilities that should be fixed on our side:
* `NotMasterError` renamed to `NotPrimaryError`
* Default CodecOptions now has `UuidRepresentation.UNSPECIFIED`. This highlighted several places in TxMongo where `codec_options` were not properly propagated from `Connection` down to `Database` and `Collection`.
* `bson` package doesn't have `PY3` symbol anymore
* `_UOP` internal symbol removed
UPD: PyMongo 4.9 released yesterday changed some it's internals, so limiting to 4.8 for now.
=> PyMongo 4+ support

docs/source/NEWS.rst, docs/source/conf.py, python-txmongo.spec, setup.py, tests/basic/test_bulk.py, tests/basic/test_collection.py, tests/basic/test_write_concern.py, txmongo/__init__.py, txmongo/collection.py, txmongo/connection.py, txmongo/database.py, txmongo/protocol.py, txmongo/pymongo_internals.py
I want to make TxMongo compatible with newer wire protocol of MongoDB 5.0+ (OP_MSG).
This would be much easier to do without supporting older protocols at the same time.
That's why I suggest to drop support of outdated and no longer supported version of Python and MongoDB. This will allow us to cleanup and simplify the codebase.
To do it nicely I suggest to release 23.0.0 with the only change of deprecation warnings when old Python or MongoDB are detected.
@psi29a what do you think about it?
=> Deprecation warnings

docs/source/NEWS.rst, tests/basic/test_queries.py, txmongo/collection.py
Raise `DeprecationWarnings` for
* insert()
* update()
* remove()
* save()
* find_and_modify()
* group()
* as_class argument to find* methods
=> DeprecationWarnings for insert(), update(), remove() and as_class

docs/source/NEWS.rst, setup.py, tox.ini
We have used `Deferred[T]` syntax in txmongo that is only available in Twisted ≥ 21.7.0.
Since this is pretty old version, I suggest to bump the minimum version.
=> Bump Twisted version to 21.7.0

docs/source/NEWS.rst, tests/basic/test_collection.py, tests/basic/test_filters.py, tests/basic/test_queries.py, txmongo/collection.py, txmongo/database.py, txmongo/filter.py, txmongo/protocol.py
Add builder-pattern methods for Cursor allowing doing queries like this:
```python
async for doc in collection.find({"size": "L"}).sort({"price": 1}).skip(10).limit(50):
print(doc)
```
=> Builder pattern methods on Cursor

docs/source/NEWS.rst, requirements.txt, tox.ini, txmongo/collection.py
Current version of TxMongo is broken when used with Twisted ≥24.10.0 because we forgot to add `"result"` to `_DEFERRED_METHODS` :(
Code to reproduce:
```python
@react
async def main(reactor):
conn = ConnectionPool()
db = conn.db
coll = db.coll
await coll.drop()
await coll.insert_one({"x": 1})
print(await coll.find())
await conn.disconnect()
```
This example hangs hardly on `await coll.find()`
=> Fix compatibility with Twisted 24.10+

.travis.yml, docs/source/NEWS.rst, setup.py, tox.ini
It turns out that Twisted prior to v22.8.0 doesn't properly support `async def` test methods — it doesn't catch failed asserts in such methods 😱  But we need a lot of `async with` in transaction tests.
There are possible workarounds for it, but 22.8.0 sounds old enough.
=> Bump minimum Twisted version to 22.8.0

docs/source/NEWS.rst, tests/advanced/test_auth.py, tests/advanced/test_replicaset.py, tests/advanced/test_transactions.py, tests/basic/test_aggregate.py, tests/basic/test_bulk.py, tests/basic/test_cancel.py, tests/basic/test_collection.py, tests/basic/test_connection.py, tests/basic/test_filters.py, tests/basic/test_queries.py, tests/basic/test_sessions.py, txmongo/_gridfs/__init__.py, txmongo/_gridfs/grid_file.py, txmongo/collection.py
=> Split count() into count_documents() and estimated_document_count()
