twisted/txmongo

MANIFEST.in, docs/source/NEWS.rst, examples/deferreds/insert-concise.py, examples/deferreds/insert.py, examples/inlinecallbacks/insert.py, tests/mongod.py, tests/test_aggregate.py, tests/test_auth.py, tests/test_collection.py, tests/test_connection.py, tests/test_filters.py, tests/test_find_and_modify.py, tests/test_objects.py, tests/test_queries.py, tox.ini, txmongo/_gridfs/__init__.py, txmongo/collection.py, txmongo/connection.py, txmongo/database.py, txmongo/filter.py, txmongo/gridfs.py, txmongo/protocol.py
- Return more in index_information, using a dict like pymongo
- Replaced xrange with range to get things future proof for python3
- pep8 as much as possible, 100 column limit
- Fixed errnos and messages
- Use " for strings and ' for single chars, just to be consistent
- Updated NEWS
=> Index information now returns all information

tests/test_filters.py, txmongo/filter.py
I suggest simplier solution for issue from #83
=> Named indexes (another try)

tests/test_queries.py
Falling back to `serverStatus.cursors.totalOpen` instead of `serverStatus.metrics.cursor.open.total` when we are on MongoDB 2.4
=> Support for old-style serverStatus command on MongoDB 2.4

tests/test_objects.py
drop collection via database
cover drop collection typeerror
=> add create_collection coverage

tests/test_objects.py
=> switch away from localhost

requirements-dev.txt, tests/mongod.py, tests/test_auth.py, tests/test_connection.py, tests/test_protocol.py, tests/test_replicaset.py, txmongo/connection.py
=> fixed string operation, added small bits of coverage

docs/source/NEWS.rst
=> Small fixes to NEWS.rst

tests/test_replicaset.py
Sometimes replicaset tests are failing with
> namespace admin.$cmd failed: all members and seeds must be reachable to initiate set
This is probably because `setUp()` method does `rs.initiate()` right after several mongod processes are started. This patch tries to address this by connecting to each started mongod to ensure all replicaset members are up and running before running `rs.initiate()`.
=> Trying to improve durability of test_replicaset.py

tests/test_replicaset.py, txmongo/connection.py
TxMongo used invalid option name
Test case also added for this scenario
=> Fixed checking Replica Set name while connecting

tests/test_auth.py
To make 100% coverage of `database.py` :)
=> Test handling invalid types of username/password

tests/test_objects.py, txmongo/collection.py
`name`, `full_name` and `database` properties added to Collection class along with unittests for them
The meanings are exactly the same as in PyMongo
=> Collection props

txmongo/collection.py
I was investigating how my server consumes RAM and noticed that each call to `find()` or `find_one()` creates unreachable reference cycle and this is (among with other reasons) why my app is constantly triggers GC.
`after_reply` inside `find_with_cursor` does some sort of deferred recursion and so references itself. This creates unobvious reference cycle between function object of `after_reply` and its closure.
Proposed solution is to break self-reference of `after_reply` by passing this reference into function via arguments. Rather tricky though, but less intrusive than moving `after_reference` to outer scope to remove closure.
Testing code:
```python
gc.disable()
print(len(gc.get_objects()))
for i in range(10000):
yield coll.find_one()
print(len(gc.get_objects()))
```
Before:
```
19813 …
```
=> Circular reference removed between after_reply and its closures

docs/source/NEWS.rst, docs/source/conf.py, python-txmongo.spec, setup.py
Changelog entry added and version changed to 16.0.0 in several places
=> 16.0.0 release

docs/source/NEWS.rst, docs/source/conf.py, python-txmongo.spec, setup.py, txmongo/_gridfs/__init__.py, txmongo/_gridfs/grid_file.py, txmongo/collection.py, txmongo/connection.py, txmongo/database.py, txmongo/filter.py, txmongo/protocol.py, txmongo/utils/__init__.py
This should help to address this: https://github.com/twisted/txmongo/issues/142
Feedback appreciated. :)
=> better logging and version bump

tests/test_queries.py, txmongo/collection.py
As @jhonny111s noticed in #145, txmongo raises `WriteError`/`DuplicateKeyError` from `insert_many`, while PyMongo raises `BulkWriteError` which allows to check which documents are not inserted.
This patch fixes makes `insert_many` to always raise `BulkWriteError` like PyMongo does, and also adds additional tests for checking exception types from all `*_one`/`*_many` methods
=> Raising BulkWriteError from insert_many instead of WriteError/DuplicateKeyError

docs/source/NEWS.rst
#146 added to changelog, because this changes API a bit
=> Changelog updated

README.rst
=> Add readthedocs link to the README

docs/source/NEWS.rst, tests/test_collection.py, tests/test_filters.py, txmongo/filter.py
Rebased #179 onto master and added some tests
=> Text index

tests/test_collection.py, txmongo/collection.py, txmongo/database.py
removed `kwargs` where it is not necessary and made `@timeout`'s `_deadline` argument explicit in most cases
=> kwargs removed where it is not necessary

docs/source/NEWS.rst, txmongo/connection.py
=> Fix dictionary changed size

.travis.yml, tests/mongod.py, tests/test_objects.py, tox.ini
Twisted versions for testing also updated.
=> Don't test on py2.7

txmongo/connection.py
Fixes exceptions while dropping pingers
Fixes #259
=> del → dict.pop

.github/workflows/txmongo.yml, .gitignore, .travis.yml, bin/run_tests_with_docker.py, docs/source/NEWS.rst, requirements.txt, tests/advanced/test_auth.py, tests/advanced/test_replicaset.py, tests/conf.py, tests/mongod.py, tox.ini, txmongo/connection.py, txmongo/protocol.py, txmongo/pymongo_internals.py, txmongo/utils/__init__.py
Merge after #288 and #290 
After PR #288 @IlyaSkriblovsky wants add support of new mongo versions. 
For simplify testing with different mongo version we wrote adapter for run mongod in docker while running tests.
=> Feat: add docker tests

docs/source/NEWS.rst
I think we're ready for release now :rocket:
=> Add date for 24.1.0 release

docs/source/NEWS.rst, tests/advanced/test_transactions.py, txmongo/connection.py, txmongo/sessions.py
=> Support for default_transaction_options start_session() option
